[target.x86_64-pc-windows-msvc]
# 使用 lld-link 取代 MSVC link.exe，避開 PDB LNK1318 問題
linker = "rust-lld.exe"

[build]
# 在使用 nightly 版本時關閉
# sccache: caused by: 檔名或副檔名太長。 (os error 206)
# rustc-wrapper = "sccache"

[net]
git-fetch-with-cli = true

[unstable]
git = true
