#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
sort_by = "natural"
show_hidden = true
show_symlink = false
linemode = "mtime"

[preview]
wrap = "yes"

[[opener.edit]]
run = "%EDITOR% %s"
desc = "$EDITOR"
block = true

[[opener.open]]
run = 'start "" %s1'
desc = "Open"
for = "windows"
orphan = true

[[opener.open]]
run = 'sudo start "" %s1'
desc = "Open with sudo"
for = "windows"
orphan = true

[[opener.open]]
run = '"C:\Program Files\Sandboxie-Plus\Start.exe" /box:__ask__ %s1'
desc = "Open With Sandboxie"
for = "windows"

[[opener.copyimage]]
# if file name contains space, it will be treated as multiple arguments
run = '{nu} --commands "clip copy-image %s"'
desc = "Copy Image to Clipboard"
for = "windows"

[[opener.get-dll]]
run = '{nu} --commands "(get-dll %s1);pause"'
desc = "Get DLL Path"
for = "windows"
block = true

[[opener.extract]]
run = "Bandizip %s"
desc = "Extract with Bandizip"
for = "windows"

[[opener.extract]]
run = "ya pub extract --list %s"
desc = "Extract here"

[[opener.extract]]
run = "ya pub augmented-extract --list %s"
desc = "Extract here(augmented)"

[[opener.nodejs]]
run = 'start {nu} --commands "node %s;pause"'
desc = "Run with Node.js"
orphan = true

[[opener.python]]
run = 'start {nu} --commands "uv run %s;pause"'
desc = "Run with Python"
orphan = true

[[opener.nushell]]
run = "start {nu} %s"
desc = "Open with Nushell"
orphan = true

[[opener.lazydocker]]
run = "lazydocker -f %s"
desc = "Open with LazyDocker"
block = true

[[opener.cargo-install]]
run = "cargo install --path %d"
desc = "Install Cargo Package"

[[opener.justfile]]
run = "just --justfile %s --choose --chooser \"fzf --multi --preview 'just --unstable --color always --justfile \"%s\" --show {}'\""
desc = "Run Justfile"
block = true

[[opener.add-to-path]]
desc = "Add to PATH"
run = '''
pwsh -Command "[Environment]::SetEnvironmentVariable('PATH', [Environment]::GetEnvironmentVariable('PATH', 'User') + ';%s', 'User')"
'''
for = "windows"

[[opener.bulk-rename]]
run = "code-insiders --wait %s"
block = true

[[opener.bulk-create]]
run = "code-insiders --wait %s"
block = true

[[open.prepend_rules]]
url = "bulk-rename.txt"
use = "bulk-rename"

[[open.prepend_rules]]
url = "bulk-create.txt"
use = "bulk-create"

[[open.rules]]
url = "*.nu"
use = [
  "nushell",
  "edit",
  "reveal",
]

[[open.rules]]
url = "**/docker-compose.yaml"
use = [
  "lazydocker",
  "edit",
  "reveal",
]

[[open.rules]]
url = "**/Cargo.toml"
use = [
  "cargo-install",
  "edit",
  "reveal",
]

[[open.rules]]
url = "**/{justfile,.justfile,*.just}"
use = [
  "justfile",
  "edit",
  "reveal",
]

[[open.rules]]
url = "*.exe"
use = [
  "open",
  "get-dll",
  "reveal",
]

[[open.rules]]
mime = "image/gif"
use = [
  "play",
  "reveal",
]

[[open.rules]]
# image
mime = "image/*"
use = [
  "open",
  "copyimage",
  "reveal",
]

[[open.rules]]
# media
mime = "{audio,video}/*"
use = [
  "play",
  "reveal",
]

[[open.rules]]
# jar file is actually a zip archive, but it's more user-friendly to open it with java
mime = "application/java-archive"
use = [
  "open",
  "extract",
  "reveal",
]

[[open.rules]]
# archive
mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
use = [
  "extract",
  "reveal",
]

[[open.rules]]
# data
mime = "*/{json,ndjson,yaml}"
use = [
  "edit",
  "reveal",
]

[[open.rules]]
# code
mime = "*/javascript"
use = [
  "nodejs",
  "edit",
  "reveal",
]

[[open.rules]]
mime = "text/python"
use = [
  "python",
  "edit",
  "reveal",
]

[[open.rules]]
mime = "inode/empty"
use = [
  "edit",
  "reveal",
]

[[open.rules]]
mime = "vfs/{absent,stale}"
use = "download"

[[open.rules]]
url = "*"
use = [
  "open",
  "edit",
  "reveal",
]

[[open.rules]]
url = "*/"
use = [
  "edit",
  "add-to-path",
  "reveal",
]

[[plugin.prepend_fetchers]]
group = "mime"
url = "local://*"
run = "mime-ext.local"
prio = "high"

[[plugin.prepend_fetchers]]
group = "mime"
url = "remote://*"
run = "mime-ext.remote"
prio = "high"

[[plugin.prepend_fetchers]]
group = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
group = "git"
url = "*/"
run = "git"

# previewers
[[plugin.prepend_previewers]]
mime = "application/xml"
run = "code"

[[plugin.prepend_previewers]]
url = "*.csv"
run = "code"

[[plugin.prepend_previewers]]
url = "*.rst"
run = "rich-preview"

[[plugin.prepend_previewers]]
url = "*.ipynb"
run = "rich-preview"

[[plugin.prepend_previewers]]
mime = "font/*"
run = "font-sample"

[[plugin.prepend_previewers]]
mime = "application/ms-opentype"
run = "font-sample"

[[plugin.prepend_previewers]]
url = "*.{otf,ttf,woff,woff2}"
run = "font-sample"

[[plugin.prepend_previewers]]
url = "**/.git/"
run = "preview-git"

[[plugin.prepend_previewers]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "application/subrip"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "application/postscript"
run = "mediainfo"

[[plugin.prepend_previewers]]
url = "*.{nu,nuon}"
run = "piper -- open --raw $env.TP | nu-highlight"

[[plugin.prepend_previewers]]
url = "*.bat"
run = "code"

# preloaders
[[plugin.prepend_preloaders]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_preloaders]]
mime = "application/subrip"
run = "mediainfo"

[[plugin.prepend_preloaders]]
mime = "application/postscript"
run = "mediainfo"

[[plugin.prepend_preloaders]]
mime = "font/*"
run = "font-sample"

[[plugin.prepend_preloaders]]
mime = "application/ms-opentype"
run = "font-sample"

[[plugin.prepend_preloaders]]
url = "*.{otf,ttf,woff,woff2}"
run = "font-sample"

# spotters
[[plugin.spotters]]
# Multi-file
mime = "multi/*"
run = "multi"

[[plugin.spotters]]
# Folder
url = "*/"
run = "folder"

# [[plugin.spotters]]
# # Code
# mime = "text/*"
# run = "code"

# [[plugin.spotters]]
# mime = "{application/{mbox,javascript,wine-extension-ini},audio/mpegurl}"
# run = "code"

[[plugin.spotters]]
url = "audio/*"
run = "spot-audio"

[[plugin.spotters]]
mime = "image/*"
run = "spot-image"

[[plugin.spotters]]
# Video
mime = "video/*"
run = "spot-video"

[[plugin.spotters]]
# Virtual file system
mime = "vfs/*"
run = "vfs"

# [[plugin.spotters]]
# # Error
# mime = "null/*"
# run = "file"

[[plugin.spotters]]
# Fallback
url = "*"
run = "spot"

[tasks]
image_alloc = 1073741824
