repos:
  - repo: local
    hooks:
      - id: update-yazi-config
        name: update-yazi-config
        pass_filenames: false
        language: system
        files: AppData/Roaming/yazi/config/yazi\.raw\.toml
        verbose: true
        entry: nu
        args:
          - .vscode/yazi-config-update.nu

      - id: update-starship-config
        name: update-starship-config
        pass_filenames: false
        language: system
        files: dot_config/\.starship\.toml
        verbose: true
        entry: nu
        args:
          - .vscode/update-starship.nu

      # - id: update-doc
      #   name: update-doc
      #   pass_filenames: false
      #   language: system
      #   files: \.(nu|md)$
      #   verbose: true
      #   entry: just
      #   args:
      #     - update-numd-doc

      - id: nu-check
        name: nu-check
        verbose: true
        language: system
        files: \.nu$
        entry: just
        args:
          - test
