# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  diffRenderers:
    - command: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  language: zh-CN
  nerdFontsVersion: "3"
# os:
# shellFunctionsFile: C:\Users\pl816\.config\nushell\config.nu
