#:tombi toml-version = "v1.1.0"

use-grammars = { except = ["embedded-template"] }
global-language-servers = ["codebook", "simple-completion-language-server"]

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.simple-completion-language-server]
command = "simple-completion-language-server"
config = {
  feature_words = false,  # enable completion by word
  feature_snippets = true,  # enable snippets
  snippets_first = true,  # completions will return before snippets by default
  case_sensitive = false,  # when true, only exact-case matches are suggested; when false, exact-case matches are just prioritized first
  snippets_inline_by_word_tail = false,  # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
  feature_unicode_input = false,  # enable "unicode input"
  feature_paths = false,  # enable path completion
  feature_citations = false  # enable citation completion (only on `citation` feature enabled)
}

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["**/*.json", "**/*.jsonc"]
schema = { allowTrailingCommas = true, allowComments = true }

[[language]]
name = "git-ignore"
file-types = [{ glob = ".git/info/sparse-checkout" }, { glob = ".gitignore_global" }, { glob = "git/ignore" }, { glob = ".git/info/exclude" }, { glob = ".ignore" }, { glob = "CODEOWNERS" }, { glob = ".config/helix/ignore" }, { glob = ".helix/ignore" }, { glob = ".*ignore" }, { glob = ".git-blame-ignore-revs" }]

[[language]]
name = "nu"
# formatter = { command = "nufmt", args = ["%{buffer_name}"] }
formatter = { command = "topiary", args = ["format", "--language", "nu"] }

[language.auto-pairs]
"(" = ")"
"{" = "}"
"[" = "]"
'"' = '"'
"'" = "'"
"`" = "`"
"<" = ">"

[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = ["simple-completion-language-server"]

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "jsonc"
formatter = { command = "prettier", args = ["--parser", "jsonc", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--parser", "scss", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "less"
formatter = { command = "prettier", args = ["--parser", "less", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml", "--stdin-filepath", "%{buffer_name}"] }

[[grammar]]
name = "nu"
source = { git = "https://github.com/nushell/tree-sitter-nu", rev = "main" }

[[grammar]]
name = "just"
source = { git = "https://codeberg.org/poliorcetics/tree-sitter-just", rev = "main" }
