words = [
    "Actix",
    "CLI",
    "HSTS",
    "TLS",
    "UDP",
    "XDG",
    "catppuccin",
    "clippy",
    "codeberg",
    "lazygit",
    "nextest",
    "numd",
    "nushell",
    "ollama",
    "rustls",
    "rustup",
    "thiserror",
    "tombi",
    "whois",
    "yazi",
]
