words = [
    "Actix",
    "CLI",
    "HSTS",
    "NOBIND",
    "TLS",
    "UDP",
    "XDG",
    "airshipper",
    "atuin",
    "autoload",
    "catppuccin",
    "chezmoi",
    "clippy",
    "codeberg",
    "lazygit",
    "nextest",
    "npx",
    "numd",
    "nushell",
    "ollama",
    "pnpm",
    "pnpx",
    "polars",
    "rustls",
    "rustup",
    "starship",
    "thiserror",
    "tmux",
    "tombi",
    "topgrade",
    "whois",
    "winget",
    "yazi",
]
