#:schema https://starship.rs/config-schema.json

format = "$time$all"
right_format = "${env_var.yazi_level}$shlvl$cmd_duration$battery$memory_usage"

add_newline = false

[battery]
disabled = false

[[battery.display]]
threshold = 50

[shlvl]
disabled = false

[git_metrics]
disabled = false

[directory]
truncation_length = 5
truncation_symbol = ".../"
read_only = " 󰌾"

[time]
disabled = false
time_format = "%R"

[env_var.yazi_level]
description = "Indicate the shell was launched by `yazi`"
variable = "YAZI_LEVEL"
symbol = " "
format = "[$symbol]($style)"
style = "yellow bold"

[status]
disabled = false

[direnv]
disabled = false
detect_files = [".envrc", ".env"]

[memory_usage]
disabled = false
