sequential = false
pipeline_placement = "start"
max_pipeline_length = 80
skip_external_parse_errors = true
explicit_optional_access = false

[groups]

[rules]
# id = "off|hint|warning|error"
unchecked_cell_path_index = "hint"
max_positional_params = "off"
redundant_nu_subprocess = "warning"
pipe_spacing = "off"
non_final_failure_check = "hint"
unchecked_get_index = "off"
# Error: Rule declared in config with id `wrap_external_with_complete` does not exist in this version.
# wrap_external_with_complete = "hint"
catch_builtin_error_try = "hint"
error_make_for_non_fatal = "off"
fragile_last_exit_code = "hint"
unhandled_external_error = "off"
dynamic_script_import = "warning"

# i use dev version of nushell, so i want to disable parse error for now
nu_parse_error = "off"
