sequential = false
pipeline_placement = "start"
max_pipeline_length = 80
skip_external_parse_errors = true
explicit_optional_access = false

[groups]

[rules]
# id = "off|hint|warning|error"
unchecked_cell_path_index = "hint"
max_positional_params = "off"
pipe_spacing = "off"
unchecked_get_index = "off"
catch_builtin_error_try = "hint"
unhandled_external_error = "off"
check_typed_flag_before_use = "hint"
list_param_to_variadic = "off"
redundant_nu_subprocess = "hint"

# i use dev version of nushell, so i want to disable parse error for now
nu_parse_error = "off"
